### ISSUE TITLE
How can I get the Postage stamp batch ID

### ISSUE THREAD

**Issue by G-Z-Ming** [ethersphere/gateway#102]
How can I get the Postage stamp batch ID

**Comment by agazso** [comment]
Normally with Bee you can use [this endpoint](https://docs.ethswarm.org/api/#tag/Postage-Stamps/paths/~1stamps/get).

Please note that on the public gateway nodes this is disabled in order to avoid abuse. If you need this functionality it is suggested to [run your own Bee node](https://docs.ethswarm.org/docs/).
