### ISSUE TITLE
How to solve cross-domain issues

### ISSUE THREAD

**Issue by G-Z-Ming** [ethersphere/gateway#103]
**I am a Swarm Bee beginner. Currently, I have a problem！**

**I run a Swarm Bee node: (Succeeded!)**
![1627293673(1)](https://user-images.githubusercontent.com/40484256/126972259-001d0937-9a2c-49ae-ad05-7c7277267523.png)
![1627293612(1)](https://user-images.githubusercontent.com/40484256/126972509-3d5dbcff-787b-4a7f-ba5f-ab6043fbfcfb.png)

**And, because the bee API URLs configured by default are consistent with my node, I haven't changed it.**
![1627293583](https://user-images.githubusercontent.com/40484256/126973199-c2410b98-62b3-4107-8d8a-ac8b21e7604e.png)

**However, after the project was run, this error occurred.**

Access to XMLHttpRequest at 'http://localhost:1633/bzz' from origin 'http://localhost:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

![1627294967(1)](https://user-images.githubusercontent.com/40484256/126974002-c2dbb6a4-d586-4559-895e-800cc1fbc036.png)

**Excuse me, How to solve this**

**Comment by agazso** [comment]
The Gateway app is meant to be run on a dedicated site with its own domain name (for example https://gateway.etswarm.org/). It's possible to run it locally if you disable CORS in the browser or add the right headers in the app, but this is not supported for everyday usage only for development.

What do you want to use the Gateway app for? If you just want to upload and download files maybe it's better to check out the [Dashboard app](https://github.com/ethersphere/bee-dashboard) because it also can do that and it also has more functionality to manage your nodes (buying postage stamp, cash out cheques etc.).

**Comment by G-Z-Ming** [comment]
Yes, I am currently in development, mainly testing the function of uploading and downloading files. But I don’t know where to add the right headers

**Comment by G-Z-Ming** [comment]
It's a success! @agazso, you reminded me, I checked my Bee node again and added this configuration item:
**cors-allowed-origins:'*'**
successfully uploaded the file locally. thank you very much!

![1627357053(1)](https://user-images.githubusercontent.com/40484256/127091484-eab78635-c35d-4d61-9d2b-d067dec25a09.png)

**Comment by agazso** [comment]
I'm happy it worked for you!
